openapi: 3.0.0
info:
  title: Treetracker Query API
  version: '1.70.6'
  description: 'The information API of Greenstand for web map client, wallet app or others'
  contact:
    name: Greenstand Support
    email: admin@greenstand.com
  license:
    name: GPL 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'
servers:
  - url: https://{environment}-k8s.treetracker.org/query
    variables:
      environment:
        default: dev
        enum:
          - dev # Development server
          - test # Test server
          - prod # Prodution server
paths:
  '/trees':
    get:
      tags:
        - Tree details
      operationId: trees
      deprecated: false
      summary: 'Get the list of trees matching the query parameters'
      description: |-
        Query trees by filters like planter, also consider pagination
        I think filter all tree by `active = true` is by default
      parameters:
        - name: offset
          in: query
          description: 'The start offset of the list, if missing, default is 0'
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
            example: 0
        - name: limit
          in: query
          description: 'The limit length of the return list, if missing, default is 20'
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            maximum: 1000
            minimum: 1
            default: 20
            example: 10
        - name: planter_id
          in: query
          description: 'Filter by unique planter ID'
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            minimum: 0
            example: 100567
        - name: organization_id
          in: query
          description: 'Filter by unique organization ID'
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            minimum: 0
            example: 123
        - name: wallet_id
          in: query
          description: 'Filter by unique wallet ID'
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: uuid
            example: 9a55f2f5-84af-4213-bfbe-ce17b123e900
        - name: tag
          in: query
          description: 'Filter by tag name'
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: conifer
        - name: startDate
          in: query
          description: 'Filter by start date'
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
            example: 2023-11-21
        - name: endDate
          in: query
          description: 'Filter by end date'
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
            example: 2023-11-25
        - name: order_by
          in: query
          description: 'Order result by specific field'
          required: false
          style: form
          explode: true
          schema:
            type: string
            default: time_created
            example: time_created
        - name: desc
          in: query
          description: 'Order result in descending order'
          required: false
          style: form
          explode: true
          schema:
            type: boolean
            default: true
            example: true
      responses:
        '200':
          description: 'Successfully retrieve the list of trees matching the query parameters'
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: 'Total count of trees satifiying the query condition'
                    example: 1
                  offset:
                    type: integer
                    example: 0
                  limit:
                    type: integer
                    example: 20
                  trees:
                    type: array
                    items:
                      $ref: '#/components/schemas/tree'
        '422':
          description: 'Invalid query parameters'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                code: 422
                message: '"limit" must be less than or equal to 1000'
  '/trees/{treeId}':
    get:
      tags:
        - Tree details
      operationId: trees-treeId
      deprecated: false
      summary: 'Get specific tree information'
      description: 'Get single tree object by unique tree identifier (either ID or UUID).'
      parameters:
        - name: treeId
          in: path
          required: true
          style: form
          explode: true
          schema:
            oneOf:
              - type: string
                format: uuid
              - type: integer
                format: int32
          examples:
            UUID:
              value: 8e426240-4bb0-4f18-8a24-c4a2953067f1
            Numeric:
              value: 1000407
      responses:
        '200':
          description: 'Successfully return the specified tree.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tree'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                code: 404
                message: 'Can not find trees by id:1'
        '422':
          description: 'Invalid request parameter'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                code: 422
                message: '"value" must be a valid GUID'
  '/trees/featured':
    get:
      tags:
        - Tree details
      operationId: get-trees-featured
      deprecated: false
      summary: 'Get featured tree list'
      description: |-
        This is some good trees bookmarked by admin, short term we will consider using a static table/file to pick up and store these tree id somewhere.

        The use case for this is that on the welcome page of web map site, we want to show a gallery of beautiful trees.
      responses:
        '200':
          description: 'Successfully return list of featured trees.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  trees:
                    type: array
                    items:
                      $ref: '#/components/schemas/tree'

  '/v2/trees':
    get:
      tags:
        - Tree details v2
      operationId: trees-v2
      deprecated: false
      summary: 'Get the list of trees matching the query parameters'
      description: |-
        Query trees by filters like planter, also consider pagination
        I think filter all tree by `active = true` is by default
      parameters:
        - name: offset
          in: query
          description: 'The start offset of the list, if missing, default is 0'
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
            example: 0
        - name: limit
          in: query
          description: 'The limit length of the return list, if missing, default is 20'
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            maximum: 1000
            minimum: 1
            default: 20
            example: 10
        - name: planter_id
          in: query
          description: 'Filter by unique planter ID'
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: uuid
            example: f300964d-50d3-4f36-ba7a-17dda749c3ba
        - name: organization_id
          in: query
          description: 'Filter by unique organization ID'
          required: false
          style: form
          explode: true
          schema:
            type: integer
            format: int32
            minimum: 0
            example: 123
        - name: wallet_id
          in: query
          description: 'Filter by unique wallet ID'
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: uuid
            example: 9a55f2f5-84af-4213-bfbe-ce17b123e900
        - name: tag
          in: query
          description: 'Filter by tag name'
          required: false
          style: form
          explode: true
          schema:
            type: string
            example: conifer
        - name: startDate
          in: query
          description: 'Filter by start date'
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
            example: 2023-11-21
        - name: endDate
          in: query
          description: 'Filter by end date'
          required: false
          style: form
          explode: true
          schema:
            type: string
            format: date
            example: 2023-11-25
        - name: order_by
          in: query
          description: 'Order result by specific field'
          required: false
          style: form
          explode: true
          schema:
            type: string
            default: time_created
            example: time_created
        - name: desc
          in: query
          description: 'Order result in descending order'
          required: false
          style: form
          explode: true
          schema:
            type: boolean
            default: true
            example: true
      responses:
        '200':
          description: 'Successfully retrieve the list of trees matching the query parameters'
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: 'Total count of trees satifiying the query condition'
                    example: 1
                  offset:
                    type: integer
                    example: 0
                  limit:
                    type: integer
                    example: 20
                  trees:
                    type: array
                    items:
                      $ref: '#/components/schemas/treeV2'
        '422':
          description: 'Invalid query parameters'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                code: 422
                message: '"limit" must be less than or equal to 1000'
  '/v2/trees/{treeId}':
    get:
      tags:
        - Tree details v2
      operationId: trees-treeId-v2
      deprecated: false
      summary: 'Get specific tree information'
      description: 'Get single tree object by unique tree identifier.'
      parameters:
        - name: treeId
          in: path
          required: true
          style: form
          explode: true
          schema:
            type: string
            format: uuid
            example: 8e426240-4bb0-4f18-8a24-c4a2953067f1
      responses:
        '200':
          description: 'Successfully return the specified tree.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/treeV2'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
              example:
                code: 404
                message: 'Can not find treetracker.tree by id:f300964d-50d3-4f36-ba7a-17dda749c3b1!'
  '/v2/trees/featured':
    get:
      tags:
        - Tree details v2
      operationId: get-trees-featured-v2
      deprecated: false
      summary: 'Get featured tree list'
      description: |-
        This is some good trees bookmarked by admin, short term we will consider using a static table/file to pick up and store these tree id somewhere.

        The use case for this is that on the welcome page of web map site, we want to show a gallery of beautiful trees.
      responses:
        '200':
          description: 'Successfully return list of featured trees.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  trees:
                    type: array
                    items:
                      $ref: '#/components/schemas/treeV2'

  '/v2/captures/{captureId}.':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get capture info
      tags: []
      operationId: captures-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/capture'
      description: get single capture object by id
  /v2/captures:
    parameters: []
    get:
      summary: get capture list by query parameters
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  captures:
                    type: array
                    items:
                      $ref: '#/components/schemas/capture'
                  total:
                    type: integer
                    description: total count of captures satifiying the query condition
                  offset:
                    type: integer
                  limit:
                    type: integer
      operationId: captures
      description: |-
        query captures by filters like grower_account_id, device_identifier, or species_id, also consider pagination. Filter all captures by `status=active` and exclude deleted
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: 'The start offset of the list, if missing, default is 0'
        - schema:
            type: integer
            maximum: 1000
            minimum: 0
          in: query
          name: limit
          description: 'The limit length of the return list, if missing, default is 25'
        - schema:
            type: string (uuid)
          in: query
          name: grower_account_id
          description: Filter by grower_account_id
        - schema:
            type: array of integers or uuids
          in: query
          name: organization_ids
          description: Filter by org id(s)
        - schema:
            type: string
          in: query
          name: startDate
          description: Filter by date range
        - schema:
            type: string
          in: query
          name: endDate
          description: Filter by date range
        - schema:
            type: string
          in: query
          name: tag
          description: Filter by tag name
        - schema:
            type: string
          in: query
          name: id
          description: Filter by id of capture
        - schema:
            type: string
          in: query
          name: tree_id
          description: Filter by tree_id
        - schema:
            type: string
          in: query
          name: species_id
          description: Filter by species_id
        - schema:
            type: string
          in: query
          name: device_identifier
          description: Filter by device_identifier
        - schema:
            type: string
          in: query
          name: wallet
          description: Filter by wallet's name value
        - schema:
            type: string
          in: query
          name: token
          description: Filter by token's id
        - schema:
            type: string
          in: query
          name: status
          description: Filter by status, only 'status=active'
        - schema:
            type: string
          in: query
          name: sort
          description: Sort by order and order_by values
  '/raw_captures/{rawCaptureId}.':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get raw-capture info
      tags: []
      operationId: raw-captures-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/field_data'
      description: get single capture object by id
  /raw_captures:
    parameters: []
    get:
      summary: get capture list by query parameters
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  captures:
                    type: array
                    items:
                      $ref: '#/components/schemas/field_data'
                  total:
                    type: integer
                    description: total count of raw-captures satifiying the query condition
                  offset:
                    type: integer
                  limit:
                    type: integer
      operationId: raw-captures
      description: |-
        query raw-captures (field_data) by filters like grower_account_id, device_identifier, or species_id, also consider pagination. Filter all raw-captures by `status=unprocessed` and exclude deleted by default
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: 'The start offset of the list, if missing, default is 0'
        - schema:
            type: integer
            maximum: 1000
            minimum: 0
          in: query
          name: limit
          description: 'The limit length of the return list, if missing, default is 25'
        - schema:
            type: string (uuid)
          in: query
          name: grower_account_id
          description: Filter by grower_account_id
        - schema:
            type: array of integers or uuids
          in: query
          name: organization_ids
          description: Filter by org id(s)
        - schema:
            type: integer
          in: query
          name: reference_id
          description: Filter by legacy tree id
        - schema:
            type: string
          in: query
          name: startDate
          description: Filter by date range
        - schema:
            type: string
          in: query
          name: endDate
          description: Filter by date range
        - schema:
            type: string
          in: query
          name: tag
          description: Filter by tag name
        - schema:
            type: string
          in: query
          name: id
          description: Filter by id of capture
        - schema:
            type: string
          in: query
          name: tree_id
          description: Filter by tree_id
        - schema:
            type: string
          in: query
          name: species_id
          description: Filter by species_id
        - schema:
            type: string
          in: query
          name: device_identifier
          description: Filter by device_identifier
        - schema:
            type: string
          in: query
          name: wallet
          description: Filter by wallet's name value
        - schema:
            type: string
          in: query
          name: token
          description: Filter by token's id
        - schema:
            type: string
          in: query
          name: status
          description: Filter by status, only 'unprocessed', 'approved', or 'rejected'
        - schema:
            type: string
          in: query
          name: sort
          description: Sort by order and order_by values
  /countries/leaderboard:
    get:
      summary: leader board of country
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  total:
                    type: number
                  countries:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        name:
                          type: string
                        count:
                          type: integer
                          description: the count of planted tree in this country
      operationId: get-countries-leader
      description: |-
        Top planting-tree countries (leader board), we will show the leader board on the welcome page of web map site. we can query the DB with SQL like this (provided by Seb):
        ```
        SELECT
          count(trees.*),region.name
        FROM
          trees
        RIGHT JOIN region ON
        st_contains(region.geom,trees.estimated_geometric_location)
        where region.type_id = 10
        group by region.name;
        ```

        But it's slow so seba and I consider pre-query the db and store the result somewhere.
    parameters: []
  /countries:
    get:
      summary: get countries by coordinates
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    total: 1
                    countries: []
                properties:
                  total:
                    type: number
                    description: total result of countries
                  countries:
                    type: array
                    items:
                      $ref: '#/components/schemas/country'
                required:
                  - total
                  - countries
      operationId: get-countries
      description: |
        get country by coordinates, currently, we use it to get the country name of a tree/location.
        if given the 'lat' and 'lon', we can query db by SQL:
        ```
        SELECT region.* FROM region, region_type
        WHERE region.type_id = region_type.id
        AND ST_Contains(region.geom, ST_GeomFromText('POINT (-13.215865333333333 8.34645033333333)',4326))
        AND  region_type.id = region.type_id AND region_type.type = 'country'
        ```
      parameters:
        - schema:
            type: number
          in: query
          name: lat
          description: the latitude of the location
        - schema:
            type: number
          in: query
          name: lon
          description: the longitude of the location
    parameters: []
  '/countries/{countryId}':
    get:
      summary: get one country
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  total:
                    type: number
                    description: total result of countries
                  countries:
                    type: array
                    items:
                      $ref: '#/components/schemas/country'
      operationId: get-countries-leader
      description: |-
        get country by id, in some case I use this to fetch the center point and move the map view to go to country

        I suppose the countryId is the key of table `region` and type_id = 'country'

        No need to return get big column like metadata and multipolygon
      parameters:
        - schema:
            type: number
          in: query
          name: lat
          description: the latitude of the location
        - schema:
            type: number
          in: query
          name: lon
          description: the longitude of the location
    parameters:
      - schema:
          type: string
        name: countryId
        in: path
        required: true
  '/planters/{planterId}':
    parameters:
      - schema:
          type: string
        name: planterId
        in: path
        required: true
    get:
      summary: get planter by id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/planter'
      operationId: get-planters-planterId
      description: |-
        get planter object by id

        'about' property: Seba says he might be able to populate this field, may be manually in the early stage
        'location?' property: I don't know if we can provide this infomation, the city/country of the planter, could be removed if impossible
  /planters:
    get:
      summary: get planter list by query parameter
      operationId: get-planters
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer
                  planters:
                    type: array
                    items:
                      $ref: '#/components/schemas/planter'
      description: ''
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: 'The start offset of the list, if missing, default is 0'
        - schema:
            type: integer
            minimum: -15
            maximum: 1000
          in: query
          name: limit
          description: 'The limit length of the return list, if missing, default is 20'
        - schema:
            type: integer
          in: query
          name: organization_id
          description: Filter by org id
        - schema:
            type: string
          in: query
  '/organizations/{orgId}':
    parameters:
      - schema:
          type: string
        name: orgId
        in: path
        required: true
    get:
      summary: get organization by id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organization'
      operationId: get-organizations-orgId
      description: |-
        Ge organization by id

        about some fields:
        'photo_url' property:kind of like a cover photo, Seb says he will find a way to populate it, maybe manually in ealy stage

        'location?': I don't know if we can provide this infomation, the city/country of the org, could be removed if impossible

        'about':Seba says he might be able to populate this field, may be manually in the early stage

        mission: Seba says he might be able to populate this field, may be manually in the early stage
  /organizations:
    get:
      summary: get organization list by query parameters
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: 'The start offset of the list, if missing, default is 0'
        - schema:
            type: integer
            minimum: -15
            maximum: 1000
          in: query
          name: limit
          description: 'The limit length of the return list, if missing, default is 20'
        - schema:
            type: integer
          in: query
          name: grower_account_id
          description: Filter by planter id
        - schema:
            type: string
          in: query
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer
                  organizations:
                    type: array
                    items:
                      $ref: '#/components/schemas/organization'
  /species:
    get:
      summary: get species list by filter/parameters
      operationId: get-species
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer
                  species:
                    type: array
                    items:
                      $ref: '#/components/schemas/species'
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: 'The start offset of the list, if missing, default is 0'
        - schema:
            type: integer
            minimum: -15
            maximum: 1000
          in: query
          name: limit
          description: 'The limit length of the return list, if missing, default is 20'
        - schema:
            type: integer
          in: query
          name: organization_id
          description: Filter by org id
        - schema:
            type: string
          in: query
          name: grower_account_id
          description: Filter by planter id
      description: "mainly if we can provide this endpoint, then we can display a species list on org or planter page, but I don't know if it is too resource consumming to query DB"
  /transactions:
    get:
      summary: get token transaction list by filter/parameters
      operationId: get-transactions
      description: "about returning wallet name, it is a pretty common use case that we need to display the wallet name in the frontend, so we'd better join and return the name of wallet"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/transaction'
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: 'The start offset of the list, if missing, default is 0'
        - schema:
            type: integer
            minimum: -15
            maximum: 1000
          in: query
          name: limit
          description: 'The limit length of the return list, if missing, default is 20'
        - schema:
            type: string
          in: query
          name: token_id
          description: Filter by token id
        - schema:
            type: string
          in: query
          name: wallet_id
          description: Filter by wallet id
  '/tokens/{tokenId}':
    get:
      summary: get token by id
      operationId: get-tokens-tokenId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
  /tokens:
    get:
      summary: get token list by filter/parameters
      operationId: get-tokens
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer
                  tokens:
                    type: array
                    items:
                      $ref: '#/components/schemas/token'
      parameters:
        - schema:
            type: integer
          in: query
          name: offset
          description: 'The start offset of the list, if missing, default is 0'
        - schema:
            type: integer
            minimum: -15
            maximum: 1000
          in: query
          name: limit
          description: 'The limit length of the return list, if missing, default is 20'
        - schema:
            type: string
          in: query
          name: wallet
          description: 'Filter by wallet, the value can be wallet name or wallet id'
        - schema:
            type: boolean
          in: query
          name: withCapture
          description: "if we need show a token list, it's usually we need display the tree linked to the token, and the planter info, and I think make this configurable might be better, so I add this switcher"
        - schema:
            type: boolean
          in: query
          name: withPlanter
          description: "if we need show a token list, it's usually we need display the tree linked to the token, and the planter info, and I think make this configurable might be better, so I add this switcher"
      description: ''
  '/wallets/{walletIdOrName}':
    get:
      summary: get wallet by id or name
      operationId: get-wallets-walletIdOrName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/wallet'
      description: 'about retunning photo_url,it would be great if we can set a wallet avatar and show it on the wallet page, maybe we can create the column, and just pick some good case to manualy fill some photo into'
  /gis/location/nearest:
    get:
      summary: get nearest gis location by filter/parameters
      operationId: get-gis-location-nearest
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
      parameters:
        - schema:
            type: integer
            minimum: 1
            maximum: 18
          in: query
          name: zoomlevel
          description: the map zoomlevel
        - schema:
            type: float
          in: query
          name: lat
          description: the latitude
        - schema:
            type: float
          in: query
          name: lon
          description: the longitude
  /gis/bounds:
    get:
      summary: get gis bounds by filter/parameters, e.g. give a planter id, get a bounds which contains all the trees in the planter
      operationId: get-gis-bounds
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bounds'
      parameters:
        - schema:
            type: string
          in: query
          name: planter
          description: get the bounds by the planter id
        - schema:
            type: string
          in: query
          name: wallet
          description: get the bounds by the wallet id or name
        - schema:
            type: string
          in: query
          name: organization
          description: get the bounds by the organization id

components:
  parameters:
    contentTypeJsonHeader:
      name: Content-Type
      in: header
      description: 'Specifies the media type of the request payload'
      required: true
      style: simple
      schema:
        type: string
        example: application/json
  schemas:
    location:
      description: A location point
      type: object
      properties:
        centroid:
          type: GeoJSON
          description: The center of the location
        'type':
          type: enum
          description: The type of location
          enum:
            - tree
            - cluster
        count:
          type: integer
          description: The number of trees in the location, just available for clusters
    bounds:
      description: A bounding box
      type: object
      properties:
        bounds:
          type: array
          description: 2 points defining the bounding box
    tree:
      description: 'A single tree object'
      type: object
      x-examples: {}
      title: 'Tree'
      properties:
        id:
          type: number
          format: int32
          example: 1000407
        time_created:
          type: string
          format: date-time
          example: 2023-08-01T02:52:25.166Z
        time_updated:
          type: string
          format: date-time
          example: 2023-08-01T02:52:25.166Z
        missing:
          type: boolean
          default: false
          example: false
        priority:
          type: boolean
          default: false
          example: false
        cause_of_death_id:
          type: integer
          format: int32
          example: null
        planter_id:
          type: integer
          format: int32
          example: 5840
        primary_location_id:
          type: integer
          format: int32
          example: 20041
        settings_id:
          type: integer
          format: int32
          example: null
        override_settings_id:
          type: integer
          format: int32
          example: null
        dead:
          type: integer
          format: int32
          default: 0
          example: 0
        photo_id:
          type: integer
          format: int32
          example: 10045
        image_url:
          type: string
          format: url
          example: https://treetracker-xxx.xxxx.com/10045.jpg
        certificate_id:
          type: integer
          format: int32
          example: 10
        estimated_geometric_location:
          description: 'Geospatial location of type `geometry` used by PostGIS.'
          type: string
          example: 0101000020E6100000A22AA6D24FB84240DE3829CC7B9C0AC
        lat:
          type: number
          example: -3.326408
        lon:
          type: number
          example: 27.439936
        gps_accuracy:
          type: integer
          format: int32
          example: 6
        active:
          type: boolean
          default: true
          example: true
        planter_photo_url:
          type: string
          format: url
          example: https://treetracker-xxx.xxxx.com/IMG_2022xxx.jpg
        planter_identifier:
          type: string
          example: handle3@test
        device_id:
          type: integer
          format: int32
          example: null
        sequence:
          type: integer
          format: int32
          example: null
        note:
          type: string
          example: test note
        verified:
          type: boolean
          default: false
          example: false
        uuid:
          type: string
          format: uuid
          example: 40b3d259-e761-4b96-97ab-2a5416b5ade2
        approved:
          type: boolean
          default: false
          example: true
        status:
          type: string
          example: planted
        cluster_regions_assigned:
          type: boolean
          default: false
          example: true
        species_id:
          type: number
          format: int32
          example: null
        planting_organization_id:
          type: integer
          format: int32
          example: 12
        payment_id:
          type: integer
          format: int32
          example: null
        contract_id:
          type: integer
          format: int32
          example: null
        token_issued:
          type: boolean
          default: false
          example: false
        morphology:
          $ref: '#/components/schemas/morphologyType'
        age:
          $ref: '#/components/schemas/ageType'
        species:
          type: string
          example: null
        capture_approval_tag:
          $ref: '#/components/schemas/captureApprovalType'
        rejection_reason:
          $ref: '#/components/schemas/rejectionReasonType'
        matching_hash:
          type: string
          example: null
        device_identifier:
          type: string
          example: 48b123d175ceeb4c
        images:
          type: object
          example: {}
        domain_specific_data:
          type: object
          example: {}
        image_url_backup:
          type: string
          format: url
          example: https://treetracker-yyy.xxxxx.com/10045.jpg
        token_id:
          type: string
          format: uuid
          example: a0bd456b-f6ab-4723-9999-a7f5e73ce543
        name:
          type: string
          example: null
        earnings_id:
          type: string
          format: uuid
          example: c7bbf680-303f-4502-bcad-5f91e6f78148
        session_id:
          type: string
          format: uuid
          example: 625f810a-924e-4ba5-869f-4b7be02d2ee0
        species_name:
          type: string
          example: null
        species_desc:
          type: string
          example: null
        country_name:
          type: string
          example: Tanzania
        country_id:
          type: integer
          format: int32
          example: 6632730
        organization_id:
          type: integer
          format: int32
          example: 1333
        organization_name:
          type: string
          example: The Kilimanjaro Project
        wallet_id:
          type: string
          format: uuid
          example: ac537e18-f067-41a1-8c4e-8d9121120364
        wallet_name:
          type: string
          example: test_wallet
    treeV2:
      description: 'A single tree object (v2)'
      type: object
      x-examples: {}
      title: 'Tree v2'
      properties:
        id:
          type: string
          format: uuid
          example: 634f7b16-f557-441f-be00-62b52731f51e
        latest_capture_id:
          type: string
          format: uuid
          example: fc81c671-1085-45e7-9c4e-c98948acb704
        image_url:
          type: string
          format: url
          example: https://treetracker-xxx.xxxx.com/10045.jpg
        lat:
          type: number
          example: -3.326408
        lon:
          type: number
          example: 27.439936
        estimated_geometric_location:
          description: 'Geospatial location of type `geometry` used by PostGIS.'
          type: string
          example: 0101000020E6100000A22AA6D24FB84240DE3829CC7B9C0AC
        gps_accuracy:
          type: integer
          format: int32
          example: 6
        morphology:
          $ref: '#/components/schemas/morphologyType'
        age:
          $ref: '#/components/schemas/ageType'
        created_at:
          type: string
          format: date-time
          example: 2023-08-01T02:52:25.166Z
        updated_at:
          type: string
          format: date-time
        estimated_geographic_location:
          description: 'Geospatial location of type `geography` used by PostGIS.'
          type: string
          example: 0101000020E6100000A22AA6D24FB84240DE3829CC7B9C0AC
        status:
          $ref: '#/components/schemas/treeStatusTypeV2'
        attributes:
          type: object
          example:
            entries:
              - dbh: ''
              - abs_step_count: -1
              - delta_step_count: 0
              - rotation_matrix: 0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
        species_id:
          type: string
          format: uuid
          example: d21384a4-e3ff-4b15-bb75-3bfa742efed1
    morphologyType:
      type: string
      enum:
        - seedling
        - direct_seedling
        - fmnr
      example: seedling
      description: >
        Morphology Type:
        * `seedling` - Seedling
        * `direct_seedling` - Direct Seedling
        * `fmnr` - Pruned/tied (Farmer Managed Natural Regeneration)
    ageType:
      type: string
      enum:
        - new_tree
        - over_two_years
      example: new_tree
    captureApprovalType:
      type: string
      enum:
        - simple_leaf
        - complex_leaf
        - acacia_like
        - conifer
        - fruit
        - mangrove
        - palm
        - timber
      example: simple_leaf
    rejectionReasonType:
      type: string
      enum:
        - not_tree
        - unapproved_tree
        - blurry_image
        - dead
        - duplicate_image
        - flag_user
        - needs_contact_or_review
    treeStatusTypeV2:
      type: string
      enum:
        - active
        - deleted
    country:
      description: ''
      type: object
      x-examples: {}
      properties:
        id:
          type: number
        name:
          type: string
          description: the name of the country
        centroid:
          type: string
          description: like POINT (-13.215865333333333 8.34645033333333)
    planter:
      description: the planter ojbect
      type: object
      x-examples: {}
      properties:
        id:
          type: number
        photo_url:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        about:
          type: string
          description: 'Seba says he might be able to populate this field, may be manually in the early stage'
        created_at:
          type: string
        location?:
          type: string
          description: "I don't know if we can provide this infomation, the city/country of the planter, could be removed if impossible"
        links:
          type: object
          properties:
            featured_trees:
              type: string
              description: |-
                Try HATEOAS here, in the app I'm using:
                /trees?planter_id=940&limit=4
            associated_organizations:
              type: string
              description: |-
                Try HATEOAS here, in the app I'm using:
                /organizations?planter_id=940
            species:
              type: string
              description: |-
                Try HATEOAS here, in the app I'm using:
                /species?planter_id=940
    organization:
      description: ''
      type: object
      x-examples:
        example-org:
          id: 1
          name: 180Earth
          photo_url: 'https://180.earth/wp-content/uploads/2020/01/Asset-1.png'
          location: 'Shirimatunda, Tanzania'
          created_at: 'November 11, 2019'
          about: 'Greenway is a Youth-Driven Environmental Protection Organization providing alternative solutions to single-use plastic and planting carbon-sucking trees for socio-economic development and reducing climate crisis. Our social work includes reforestation, landscape restoration, climate education, awareness campaign, conducting research, outreach activities, and collaborating with key stakeholders to implement sustainable solutions.'
          mission: 'To combat climate change, desertification, land degradation, carbon emission by inspiring healthier communities affected by severe climate disorder and modestly reducing pollution by 2050.'
      properties:
        id:
          type: number
        name:
          type: string
        logo_url:
          type: string
        photo_url:
          type: string
          description: 'kind of like a cover photo, Seb says he will find a way to populate it, maybe manually in ealy stage'
        location?:
          type: string
          description: "I don't know if we can provide this infomation, the city/country of the org, could be removed if impossible"
        created_at:
          type: string
        about:
          type: string
          description: 'Seba says he might be able to populate this field, may be manually in the early stage'
        mission:
          type: string
          description: 'Seba says he might be able to populate this field, may be manually in the early stage'
        links:
          type: object
          properties:
            featured_trees:
              type: string
              description: |-
                Try HATEOAS here, in the app I'm using:
                /trees?organization_id=1&limit=4
            associated_planters:
              type: string
              description: |-
                Try HATEOAS here, in the app I'm using:
                /planters?organization_id=1&limit=4
            species:
              type: string
              description: |-
                Try HATEOAS here, in the app I'm using:
                /species?organization_id=1
    species:
      title: species
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        count:
          type: integer
          description: "It would be great if we can display how many trees in this species has been planted by org or planter, but I don't know if it is too resource consumming to query DB"
    transaction:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 1
          token_id: 1
          source_wallet_id: 1
          destination_wallet_id: 2
          source_wallet_name: apple
          destination_wallet_name: orange
          processed_at: '2018-02-28'
      properties:
        id:
          type: string
        token_id:
          type: string
        source_wallet_id:
          type: string
        destination_wallet_id:
          type: string
        source_wallet_name:
          type: string
          description: "it is a pretty common use case that we need to display the wallet name in the frontend, so we'd better join and return the name of wallet"
        destination_wallet_name:
          type: string
        processed_at:
          type: string
        claim:
          type: boolean
          description: if possible
        transfer_id:
          type: string
    token:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 1
          wallet_id: 0248f77a-1531-11ec-82a8-0242ac130003
          capture_id: 186734
          capture_photo_url: 'https://treetracker-dev-images.s3.eu-central-1.amazonaws.com/2020.10.19.09.50.38_-5.508172399749922_38.98146973686408_6bebe71e-5369-4ae0-8c47-9eeff6599fb0_IMG_20201019_094615_7537040365910944885.jpg'
          planter_id: 940
          planter_first_name: 'Sebastian '
          planter_last_name: Gaertner
          planter_photo_url: 'https://treetracker-dev-images.s3.eu-central-1.amazonaws.com/2020.10.19.09.47.53_-5.508107173727935_38.981361706266256_39f0cc9d-0f13-4547-8142-150f15cabb67_IMG_20201019_094513_6614320100195503436.jpg'
          created_at: '2018-01-01'
      properties:
        id:
          type: number
        wallet_id:
          type: string
        capture_id:
          type: number
        capture_photo_url:
          type: string
        planter_id:
          type: number
        planter_first_name:
          type: string
        planter_last_name:
          type: string
        planter_photo_url:
          type: string
        created_at:
          type: string
    wallet:
      description: ''
      type: object
      x-examples:
        example-1:
          id: 0248f77a-1531-11ec-82a8-0242ac130003
          name: 180Earth
          token_in_wallet: 22
          photo_url: "'https://180.earth/wp-content/uploads/2020/01/Asset-1.png"
      properties:
        id:
          type: string
        name:
          type: string
        photo_url:
          type: string
          description: it would be great if we can set a wallet avatar and show it on the wallet page

    errorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
  responses:
    UnsupportedMediaTypeError:
      description: Invalid content type
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          example:
            code: 415
            message: 'Invalid content type. API only supports application/json'

  examples:
    tree933042:
      value:
        id: 933042
        photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.19.09.49.19_-4.881696978000001_38.37997515399998_47fc629b-27e9-4b58-b31a-3a35e5bbc3f0_IMG_20210518_121452_1024002290.jpg'
        verified: true
        token_id: d4bb294b-8c75-4e0f-af43-1cd9a35e1033
        impact_manager_id: 8599f832-145e-11ec-82a8-0242ac130003
        impact_producer_id: a0b6b70e-145e-11ec-82a8-0242ac130003
        created_at: '5/18/2021, 5:14:48 PM'
        lat: -4.881696978000001
        lon: 38.37997515399998
        species: Markhamia lutea
        planter_id: 5
    tree932946:
      value:
        id: 932946
        photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
        verified: true
        token_id: c488301f-1117-48c3-8866-3c38f28d3f25
        created_at: '5/17/2021, 9:31:17 PM'
        lat: -4.882294219999999
        lon: 38.380733454
        species: eucalyptus
        planter_id: 5
        organization_id: 1
    planter5:
      value:
        id: 5
        photo_url: 'https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2021.05.11.18.37.00_-4.91963284_38.52757506_adc35f9c-b76e-4798-b587-70f5fba06b89_IMG_20210511_101502_-1595081185.jpg'
        name: Issa H
    org1:
      value:
        id: 1
        name: 180Earth
        photo_url: 'https://180.earth/wp-content/uploads/2020/01/Asset-1.png'
        area: Shirimatunda
        country: Tanzania
        created_at: 'November 11, 2019'
        about: 'Greenway is a Youth-Driven Environmental Protection Organization providing alternative solutions to single-use plastic and planting carbon-sucking trees for socio-economic development and reducing climate crisis. Our social work includes reforestation, landscape restoration, climate education, awareness campaign, conducting research, outreach activities, and collaborating with key stakeholders to implement sustainable solutions.'
        mission: 'To combat climate change, desertification, land degradation, carbon emission by inspiring healthier communities affected by severe climate disorder and modestly reducing pollution by 2050.'
